import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Header from "./components/Header";
import { Toaster } from "react-hot-toast";
import SessionWrapper from "@/app/components/SessionWrapper";
import { CartProvider } from "@/app/contexts/CartContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}
      >
        <SessionWrapper>
          {/* @ts-expect-error */}
          <CartProvider>
            <Header />
            {children}
            <Toaster position="top-right" reverseOrder={false} />
          </CartProvider>
        </SessionWrapper>
      </body>
    </html>
  );
}
